name: Overkill Projects static page

on:
  push:
    branches: [main]

jobs:
  deploy-site:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.4]

    steps:
      - name: Checkout of Overkill Projects site
        uses: actions/checkout@v2

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install deps
        run: npm installed

      - name: Build
        run: npm run build
