name: Overkill Projects static page

on:
  push:
    branches: [main]

jobs:
  deploy-site:

    runs-on: ubuntu-latest

    steps:
      - name: Deploy site
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            git clone git clone git@github.com:jacobw56/ok_site.git
            cd ok_site
            npm install
            npm run build
            cp -rf build/* /var/www/overkillprojects.com/
            cd ..
            rm -rf ok_site
