name: Overkill Projects static page

on:
  push:
    branches: [main]

jobs:
  deploy-site:

    runs-on: ubuntu-latest

    steps:
      - name: Deploy site
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd ~/ok_site/
            git pull git@github.com:jacobw56/ok_site.git
            npm run build
            cp -rf build/* /var/www/overkillprojects.com/
